[tool.ruff]
line-length = 120
fix = true
lint.select = ["E", "F", "I", "UP", "B", "C4", "SIM", "RUF"]
lint.ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true

[tool.bandit]
skips = ["B101", "B608"]
exclude_dirs = ["tests"]
