[tool.ruff]
line-length = 90
fix = false
lint.select = [
    "E",
    "F",
    "I",
    "B",
    "C4",
    "SIM",
    "RUF",
    "PL",
    "ANN",
    "ARG",
    "N",
    "ANN",
]
exclude = ["tests", "streamlit", "notebooks"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true

[tool.bandit]
skips = ["B101", "B608"]
exclude_dirs = ["tests", "streamlit"]
